version: '3.7'

# ==============================================================================
# SERVICES
#
services:
    # --------------------------------------------------------------------------
    # MySQL
    #
    mysql:
        image: 'docker-lemp-mysql:1.0.0'
        container_name: 'docker-lemp-mysql'
        environment:
            - 'MYSQL_DATABASE=sample'    # データベース名
            - 'MYSQL_USER=user'          # ユーザーID
            - 'MYSQL_PASSWORD=user'      # ユーザーパスワード
            - 'MYSQL_ROOT_PASSWORD=root' # MySQLルートパスワード
    # --------------------------------------------------------------------------
    # nginx
    #
    nginx:
        image: 'docker-lemp-nginx:1.0.0'
        container_name: 'docker-lemp-nginx'
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - 'php'
        volumes:
            - './docker/nginx/conf.d:/etc/nginx/conf.d/:ro'
            - './docker/nginx/ssl/:/etc/nginx/ssl/:ro'
            - './html/:/var/www/html/'
    # --------------------------------------------------------------------------
    # PHP
    #
    php:
        image: 'docker-lemp-php:1.0.0'
        container_name: 'docker-lemp-php'
        depends_on:
            - 'mysql'
        volumes:
            - './html/:/var/www/html/'

# ==============================================================================
# VOLUME
#
# volumes:
#     www:
#         driver: 'local'
#         driver_opts:
#             type: 'none'
#             device: './www/'
#             o: 'bind'

# services:
#     mysql:
#         container_name: ${COMPOSE_PROJECT_NAME}_mysql
#         # restart: always
#         build:
#             context: ./docker/mysql
#         environment:
#             MYSQL_DATABASE: ${DB_DATABASE}
#             MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#             MYSQL_USER: ${DB_USERNAME}
#             MYSQL_PASSWORD: ${DB_PASSWORD}
#         ports:
#             - "${HOST_DB_PORT}:3306"
#         volumes:
#             # share
#             - ./docker/mysql/share:/usr/share/docker
#             # config
#             - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
#             # data
#             - ./db-data/:/var/lib/mysql/
#         logging:
#             driver: "json-file"
#             options:
#                 max-size: "200k"
#                 max-file: "10"
#     nginx:
#         container_name: "${COMPOSE_PROJECT_NAME}_nginx"
#         # restart: "always"
#         build:
#             context: ./docker/nginx
#             args:
#                 - "USER_NAME=${USER_NAME}"
#                 - "USER_UID=${USER_UID}"
#         ports:
#             - "${HOST_HTTP_PORT}:80"
#             - "${HOST_HTTPS_PORT}:443"
#         depends_on:
#             - "php"
#         volumes:
#             # share
#             - ./docker/nginx/share:/usr/share/docker
#             # log
#             - ./logs/nginx:/var/log/nginx
#             # config
#             - ./docker/nginx/config/nginx.conf:/usr/template/nginx.conf
#             - ./docker/nginx/config/sites-enabled:/etc/nginx/conf.d/
#             - ./docker/nginx/config/ssl/:/etc/nginx/ssl/
#             # www data
#             - ./www:/var/www/html
#             # www data (excludes)
#             - ./exclude:/var/www/html/sys/resources/assets
#         environment:
#             - "USER_NAME=${USER_NAME}"
#             - "USER_UID=${USER_UID}"
#         logging:
#             driver: "json-file"
#             options:
#                 max-size: "200k"
#                 max-file: "10"
#     php:
#         container_name: "${COMPOSE_PROJECT_NAME}_php"
#         # restart: "always"
#         build:
#             context: ./docker/php
#             args:
#                 - "USER_NAME=${USER_NAME}"
#                 - "USER_UID=${USER_UID}"
#         depends_on:
#             - "mysql"
#         volumes:
#             # share
#             - ./docker/php/share:/usr/share/docker
#             # config
#             - ./docker/php/startup.sh:/usr/local/bin/startup.sh
#             - ./docker/php/config/php-fpm.conf:/usr/template/zzz-docker.conf
#             - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
#             # www data
#             - ./www:/var/www/html
#             # www data (excludes)
#             - ./exclude:/var/www/html/sys/resources/assets
#         environment:
#             - "USER_NAME=${USER_NAME}"
#             - "USER_UID=${USER_UID}"
#         logging:
#             driver: "json-file"
#             options:
#                 max-size: "200k"
#                 max-file: "10"
#     phpmyadmin:
#         container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
#         image: phpmyadmin/phpmyadmin
#         ports:
#             - 8080:80
#         depends_on:
#             - "mysql"
#         environment:
#             PMA_HOST: mysql
#             MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#     mailcatcher:
#         container_name: "${COMPOSE_PROJECT_NAME}_mailcatcher"
#         image: schickling/mailcatcher
#         depends_on:
#             - nginx
#             - php
#             - mysql
#         ports:
#             - 1080:1080
#             - 1025:1025
# volumes:
#     www-data:
#         driver: local
#         driver_opts:
#             type: none
#             o: bind
#             # type: nfs
#             # o: addr=host.docker.internal,actimeo=1
#             device: ":${PWD}/www"
